services:
  - type: web
    name: arabic-character-recognition
    env: python
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONUNBUFFERED
        value: 1
      - key: UPLOAD_DIR
        value: ./uploads
      - key: DEBUG
        value: "False"
      - key: PYTHONPATH
        value: /opt/render/project/src
