services:
  - type: web
    name: arabic-character-recognition
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: DEBUG
        value: "False"